[package]
name = "wasmbin"
version = "0.1.0"
authors = ["Ingvar Stepanyan <rreverser@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leb128 = "0.2.4"
thiserror = "1.0.9"
wasmbin-derive = { path = "derive" }
custom_debug = "0.4.0"
once_cell = "1.3.1"
arbitrary = { version = "0.4.1", features = ["derive"] }

[features]
default = ["lazy-blob"]
lazy-blob = []
nightly = ["criterion/real_blackbox", "wasmbin-derive/nightly"]
tail-call = []
bulk-memory-operations = []
simd = []

[dev-dependencies]
criterion = "0.3.1"
libtest-mimic = "0.2.0"
wast = "17.0.0"

[[bench]]
name = "bench"
harness = false

[profile.bench]
debug = true

[[test]]
name = "spec"
harness = false
