[package]
name = "wasmbin"
version = "0.1.0"
authors = ["Ingvar Stepanyan <rreverser@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leb128 = "0.2.4"
thiserror = "1.0.9"
wasmbin-derive = { path = "derive" }
custom_debug = "0.4.0"
once_cell = "1.3.1"

[dev-dependencies]
memmap = "0.7.0"

[features]
default = ["lazy-blob"]
lazy-blob = []
