name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run tests with proposals enabled
      run: cargo test --verbose --features=proposals -- -q
    - name: Install and switch to nightly Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: clippy
        toolchain: nightly
        override: true
    - name: Run `clippy check`
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features --all-targets
